export const LOGIN_START = "LOGIN_START";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILED = "LOGIN_FAILED";

export const START_LOADING = "START_LOADING";
export const STOP_LOADING = "STOP_LOADING";
export const FETCH_TYPE_PRODUCT = "FETCH_TYPE_PRODUCT";
export const FETCH_PRODUCT_BY_TYPE = "FETCH_PRODUCT_BY_TYPE";
export const FETCH_DETAIL = "FETCH_DETAIL";
export const ADD_CART = "ADD_CART";
export const DELETE_CART = "DELETE_CART";
export const NUMBER_QUANTITY = "NUMBER_QUANTITY";
export const FETCH_TYPE_COMBO_PRODUCT = "FETCH_TYPE_COMBO_PRODUCT";
export const FETCH_COMBO_BY_LINK = "FETCH_COMBO_BY_LINK";
export const FETCH_DETAIL_COMBO = "FETCH_DETAIL_COMBO";
export const FETCH_SUPPLIER_TYPE = "FETCH_SUPPLIER_TYPE";
export const FETCH_PRODUCT_SUPPLIER_BY_TYPE = "FETCH_PRODUCT_SUPPLIER_BY_TYPE";
export const FETCH_DETAIL_SUPPLIER = "FETCH_DETAIL_SUPPLIER";
